import pandas as pd

def classification(df1: pd.DataFrame):
    df = df1
    # Definisci le categorie
    categorie = {
        'failure device instructions': ['driving vehicle hov lane authorized traffic control device',
                                        'driver failure obey traffic device making turn',
                                        'traffic control device instructions'],
        'window': ['driving motor veh obstructed windshield', 'driving unsafe veh hwy',
                   'driving hwy objmaterialobstruct hangingfrom rearview mirror interfering wclear view',
                   'installing window tinting material compliance requirements',
                   'operating vehicle highway unauthorized window tinting material',
                   'parking veh prohibited official sign',
                   'operating veh temporary parking placard hanging inside rearview mirror',
                   'driving hwy obstructed windshield view', 'driving veh windshield view obstructed sign material',
                   'driving veh window view obstructed sign material',
                   'driving vehicle removable windshield placard hanging inside rearview mirror', 'window tint',
                   'operating vehicle highway unauthorized window tinting material',
                   'installing window tinting material compliance requirements'],
        'exceeding speed': ['failure reduce speed curve', 'failure reduce speed dangerous highway conditions', '75 55',
                            'speed greater reasonable', 'driving veh excess reasonable prudent speed hwy',
                            'driving vehicle excess reasonable prudent speed highway', 'exceeding maximum',
                            'exceeding posted', 'exceeding highway work zone speed limit'],
        'failure registration card': ['failure display registration card upon demand police officer'],
        'problem vehicle light': ['motor veh trailer combination end veh', 'failure dim lighted head lamps parked veh',
                                  'reverse lights inoperative', 'stoplight light inoperative',
                                  'right front clearance light inoperative',
                                  'tag light right front side marker 3 3 id inoperative', 'taillight inoperative',
                                  'rear id light',
                                  'headlight turn signal id light clearance light marker light inoperative',
                                  'headlight inoperative', 'headlight aim', 'veh hwy operation inadequate rear',
                                  'driver failure reduce light distribution within',
                                  'driver failure avoid projecting glaring light', 'dash light',
                                  'driving vehequipment hwy lamp deviceimproperly displaying white light rear',
                                  'inop lt head lamp', 'vehicle lamp projecting glaring dazzling light',
                                  'driving veh hwy lamp displaying white light rear',
                                  'use lamps motor veh changing original performance',
                                  'driver failure use signal lamp turn',
                                  'driving veh hwy lamp improperly displaying white light rear',
                                  'reverse lamp stop lamps inoperable',
                                  'driving veh hwy lamp device improperly displaying white light rear',
                                  'failure equip veh required rear stop lamp',
                                  'failure properly equip locate headlamps motor veh',
                                  'motor veh trailer semitrailer pole trailer wo required stop lamps equipment',
                                  'failure properly equip locate headlamps motor veh',
                                  'failure equip veh required rear stop lamp',
                                  'rear side markers front left turn 1 rear id tag lamp inoperable',
                                  'hazard warning lamp', 'backup lamp', 'emergency warning lamp', 'id lamp',
                                  'side marker lamp', 'lighted lamps illuminating device', 'tag light',
                                  'veh failure display reflect amber color light lamps reflectors req',
                                  'trailer wo required stop lamps equipment',
                                  'motor veh wo required stop lamps equipment',
                                  'failure display two lighted front lamps required',
                                  'failure display reflect red color light rear lamps reflectors req',
                                  'clearance lamps', 'fog auxilary lamps', 'parking lamps',
                                  'failure equip hwy veh required lamps reflectors'],
        'careless driving': ['failure driver slow reasonable prudent speed passing stopped emerg veh',
                             'failure driver make lane change availablelane immed adjacent stopped emerg veh',
                             'drive across private property purpose avoiding traffic control device',
                             'directing or permitting the operation of a highway vehicle contrary to the law',
                             'failure veh yield intersection rightofway another veh', 'standing veh intersection',
                             'driver failure exercise due care avoid pedestrian collision',
                             'driver making prohibited uturn crest grade', 'following veh closely',
                             'failure drive right center', 'driver starting veh stopped position unsafe',
                             'driver fail yield intersection rightofway veh turn red',
                             'driver failure enter lawful lane left turn',
                             'driving left turn lane longer distance necessary',
                             'driver use motor veh horn hwy reasonably necessary safety',
                             'driver fail yield intersection rightofway pedestrian turn red', 'reckless driving',
                             'failure yield right way left turn', 'negligent driving', 'aggressive driving',
                             'improper passing overtaken vehicle', 'unsafe passing right overtaken veh',
                             'unsafe backing motor veh', 'driving left roadway center overtaking passing unsafe',
                             'causing standing veh obstruct free veh passage roadway',
                             'driving left side roadway posted passing zone marked pavement striping',
                             'driving roadway passing vehicle', 'driving unsecured loaded veh',
                             'driving wrong wayone way street',
                             'person driving motor veh hwy wo tires safe operating condition required adm',
                             'driving motor veh hwy publicly wearing earplugs ears',
                             'driving left side roadway posted passing zone marked pavement striping',
                             'driving wrong wayone way street', 'driving motor vehicle roadway passing vehicle',
                             'prohibited double parking', 'driver making improper turn intersection',
                             'left turn improper road position', 'driver failing make left turn left turn lane',
                             'rt turn improper road position', 'turn signals', 'driver reading text',
                             'driver turning vehicle without giving appropriate signal required',
                             'driver failing give turn signal continuously last 100 travel turning',
                             'driver reading electronic msg oper veh travel portion hwy',
                             'driver turning left fail yield right',
                             'driver readingelectronic msg oper veh travel portion hwy',
                             'driver writingsendingreading textelectronic msg oper veh travel portion hw',
                             'river turning veh without giving adequate signal',
                             'driver turning left fail yield right way vehicle approaching opposite direction',
                             'failure dr make lane ch',
                             'driver motor vehicle following vehicle closer reasonable prudent',
                             'driver changing lanes prohibited traffic control device', 'driver changing lanes unsafe',
                             'unsafe lane changing', 'failure drive vehicle right half roadway required',
                             'negligent driving vehicle careless imprudent manner',
                             'driver using hands use handheld telephone whilemotor vehicle motion'],
        'administration problem': ['owner failure return adm suspended reg card',
                                   'failure obligor register insurance commissioner year',
                                   'failure motor veh driver furnish written id info',
                                   'knowingly giving false accident report information',
                                   'driver record duty status current',
                                   'driver oper mv prior repairing outofsvc defect',
                                   'falsifyingattempt falsify fraudulent intent official documentplate issued ad',
                                   'person knowingly making false veh theft report police',
                                   'failure mv oper present evidence required security request law enforcement officer',
                                   'failure veh owner furnish adm required insurance evidence bodily injury accident',
                                   'owner motor scooter failure displaydecal vehicle prescribed mva',
                                   'fail refuse surrender adm lawful demand suspended lic', 'notify adm address',
                                   'failure display tab plates veh required adm', 'notify administration'],
        'driving alcohol': ['driving impaired controlled dangerous substance',
                            'driving attempting drive veh far impaired alcohol',
                            'driving veh far impaired drugs drive safely',
                            'driving attempting drive motor vehicle alcohol',
                            'driving motor veh alcohol blood violation restriction.',
                            'driving veh impaired controlled dangerous substance',
                            'driving attempting drive motor vehicle alcohol', 'alcohol'],
        'license problem': ['failing perform required act pertaining drivers lic',
                            'violating provisional lic restriction',
                            'person driving motor veh hwy public use property suspended lic privilege',
                            'person driving motor vehicle highway public use property suspended outofstate license',
                            'knowingly permitting veh persons control driven hwy unauthorized person',
                            'driving motor veh without valid medical examiners certificate possession',
                            'drivingattempting drive motor veh hwy wo req license authorization',
                            'violating lic restriction', 'failure individual driving hwy licwith',
                            'owner knowingly permitting motor veh driven hwy unauthorized person', 'driving susp',
                            'fail display license demand', 'forbidden act pertaining drivers lic',
                            'holder noncommercial class c dr lic driving hwy mv type auth lic',
                            'possessing one drivers license one time',
                            'driving commercial motor veh wo commercial drivers license possession',
                            'driving vehicle violation restricted license requirement',
                            'display cause permit displayed suspended lic',
                            'person driving motor veh hwy suspended lic privilege', 'display suspended lic',
                            'licensee failure apply dup lic lic', 'driving lic susp', 'driving motor veh lic suspended',
                            'possessing suspended lic',
                            'holder learners permit driving unauthorized person occupying front seat',
                            'holder learners permit driving un authorized person occupying front seat',
                            'holder learners permit driving wo req supervision',
                            'failure individual driving highway display license uniformed police demand',
                            'revoked outofstate license', 'person driving motor vehicle license suspended',
                            'without required license authorization', 'revoked license privilege',
                            'suspended license privilege', 'expired license'],
        'sign violation': ['driver failure stop sidewalk emerging driveway',
                           'driver failure yield right way entering hwy private driveway',
                           'park desig indiv wdisibilities space wo special reg platewindshield placard auth use',
                           'driver fail make required stop pavement mark',
                           'driver making improper left turn red signal', 'driver failing stop red signal left turn',
                           'driver fail stop flashing red traffic signal stop line',
                           'failure stop stopped school veh operating alternately flashing red lights',
                           'parking veh hwy outside business residential district',
                           'failure driver crossover yield right',
                           'failure to yield at an intersection or give right-of-way to another vehicle',
                           'failure stop yield thru hwy', 'driver failure stop entering', 'standing parking veh within',
                           'parking veh front private driveway wo owners consent', 'parking veh wi 30 ft stop sign',
                           'driver failure obey designated lane directions', 'failure stop entering highway',
                           'driver failure stop pedestrian crosswalknot contributing accident',
                           'driver passing veh stopped pedestrian crosswalk',
                           'fail yield intersection rightofway green traffic signa',
                           'making vehicular turn authority highway prohibited sign',
                           'failure driver yield rightofway police veh using signals',
                           'failure driver drive curb upon signal',
                           'driver failure yield rightofway intersection yield sign',
                           'failure yield rightofway pedestrian',
                           'stopping standing parking veh prohibited official sign',
                           'parking veh wherever prohibited official', 'parking prohibited official signs',
                           'failure yield right way left turn', 'stopping veh crosswalk',
                           'driver failure stop pedestrian crosswalk', 'stop sign', 'stop sign line',
                           'flashing red traffic signal without stopping'],
        'belts': ['operator failure use seat belt',
                  'person md reg vehicle failing transport child weighing 40 lbs less child safety seat',
                  'safety belts', 'fail transport child age 16 seat belt',
                  'oper motor veh occupant 16 restrained seat belt', 'passenger age 16 outboard front seat',
                  'passenger age 16 rear seat',
                  'failing secure child age 8 child safety seat transporting motor vehicle',
                  'failing secure child age 8 child safety seat transporting motor vehicle',
                  'operator restrained seatbelt', 'operator restrained seat belt', 'occupant 16 restrained seatbelt'],
        'other': ['driving motor vehicle able comply english speaking requirements', 'throwing refuseon hwy',
                  'driving motor veh hwy wearing earplugs ears',
                  'operating motor vehicle without proper required ememergency equipment power unit',
                  'driving rented motor vehicle violation rental agreement',
                  'veh entering intersection occupied funeral procession', 'abandoning veh public property',
                  'directing permitting hwy veh operation contrary law',
                  'attempt driver elude police official police veh',
                  'willfully disobeying lawful order direction police officer', 'driving veh wearing earphones',
                  'failure dr slow reasonable prudent speed passing stopped emerg veh',
                  'willfully driving motor veh slow speed impeding normal reasonable traffic movement',
                  'throwing discharge refuseon hwy', 'person driving hwy veh visible blue',
                  'driving veh hwy excessive weight exceed', 'driving veh speed contest hwy',
                  'failure to have a loaded highway vehicle safely loaded',
                  'motor carrier fail correct defects noted inspection report',
                  'driver permitting person occupy area vehicleprimarily intended carry cargo',
                  'driver failing prevent loss load',
                  'driver permitting person occupy area vehicleprimarily intended carry cargo',
                  'operating mv wo proper required emergency roadside warning devices',
                  'veh driver giving false fictitious name uniformed police', 'low air warning device',
                  'lift axle airtoweight ratio', 'attempt driver elude uniformed police',
                  'owner failure maintain required security veh reg period',
                  'unlawful use historic passenger veh general daily transportation',
                  'unlawful use historic truck general daily transportation',
                  'failure driver drive curb upon signal police veh', 'possessing fictitious lic',
                  'driving veh hwy wo required minimum equipment', 'holder learners permit driving wo req supervision',
                  'stoplight inoperative', 'failure control vehicle speed highway avoid collision',
                  'failure control veh speed hwy avoid collision'],
        'problem vehicle': ['installation battery improper', 'operating motor vehicle fabric exposed tread tire',
                            'operating motor vehicle flat tire', 'failure loaded hwy veh safely loaded',
                            'frame commercial vehicle cracked loose sagging broken', 'suspension shocks',
                            'op veh hwy wtailgate not',
                            'driving veh pub maintained hwy excess gross wt exceeds allowable', 'door latchhandle',
                            'speedometer odometer', 'emergency braking system operating properly',
                            'driver spinning wheels', 'brake hose inadequate leaking', 'ext air brake component',
                            'failure equip motorcycle two rear view mirrors', 'wheels lugs',
                            'emergency braking system operating properly', 'fuel system', 'floor trunk pan',
                            'wheel alignment', 'failure equip motor veh adequate vision outside mirror',
                            'fenders flaps', 'motor veh equipped unlawfully modified exhaust system',
                            'driving veh equipped ignition interlock required program',
                            'driving motor vehicle without lighted head lamps fog lights operating windshield wipers',
                            'driving veh hwy wo required minimum equipment', 'using device motor veh exhaust',
                            'operating motor vehicle without adequate horn', 'windshield wipers',
                            'vehicle brake system', 'exhaust system', 'rearview mirrors',
                            'operating motor vehicle inadequate', 'driving veh hwy wo required minimum equipment'],
        'omission of assistance': ['failure return remain scene',
                                   'fail veh driver accto rptbodily injattended veh damageprop damageto nearest police',
                                   'fail veh driver accto rpt', 'failure immediately stop veh scene',
                                   'failure stop accident involving damage attended veh', 'failure veh driver stop',
                                   'failure veh driver accident', 'failure veh driver involved accident'],
        'registration problems': ['allowing vehicle driven hwy unpaid registration fee',
                                  'driving veh hwy suspended reg', 'owner failure apply adm reg veh subject reg',
                                  'driving unregistered trailer highway', 'driving veh hwy unpaid registration fee',
                                  'allowing veh driven hwy suspended registration',
                                  'owner failure surender reg evidences within', 'susp reg', 'currant reg card',
                                  'failure veh driver carry current reg card', 'fraudulently applying veh reg',
                                  'failure carry registration card within vehicle', 'driving suspended registration',
                                  'operating unregistered motor vehicle',
                                  'owner knowingly permitting driven uninsured vehicle', 'driving uninsured vehicle',
                                  'knowingly driving owner knowingly permitting driven uninsured vehicle',
                                  'knowingly driving uninsured vehicle', 'suspended registration',
                                  'operating unregistered motor vehicle highway'],
        'tag problem': ['failure properly position registration plate vehicle',
                        'displaying permitting displayed reg plate issued vehicle',
                        'obsuring vehicle registration plate wintent avoid id', 'driving wo current tags',
                        'failure properly maintain fasten veh reg plate visible position',
                        'knowingly holding falsified veh reg plate', 'curr plate',
                        'attaching unauthorized veh reg plate intentto misrepresent veh owner',
                        'driving vehicle highway without current registration plates validation tabs',
                        'failure securely fasten registration plate vehicle',
                        'failure properly place position registration plate vehicle',
                        'failure properly maintain fasten vehicle registration plate visible position',
                        'displaying reg plate issued vehicle', 'displaying reg plate issued vehicle person.',
                        'unauthorized display use registration plate', 'failure display proper vehicle id',
                        'failure maintain legible registration plate free covers', 'failing display proper vehicle id',
                        'failure properly maintain fasten vehicle registration plate visible position',
                        'failure securely fasten properly place position registration plate vehicle',
                        'failure properly place position registration plate vehicle',
                        'failure securely fasten registration plate vehicle',
                        'unauthorized display use registration plate', 'failure maintain legible registration plate',
                        'driving veh wo adequate rear reg plate illumination',
                        'failure maintain legible registration plate free covers', 'failing display proper vehicle id',
                        'permitting veh driven hwy wo current registration validation tabs issued adm',
                        'failure attach veh reg plates front rear',
                        'failure attach vehicle registration plates front rear',
                        'without current registration plates validation tabs', 'displaying expired registration plate',
                        'displaying reg plate issued vehicle', 'displaying reg plate issued vehicle person',
                        'displaying registration plate issued vehicle'],
        'stop lights': ['stop lights', 'stop red traffic signal', 'stop steady circular red signal',
                        'stop steady red arrow signal'],
    }

    # Aggiungi una colonna 'categoria' al DataFrame
    df['category'] = None

    # Assegna ogni violazione a una categoria
    for categoria, parole_chiave in categorie.items():
        for parola_chiave in parole_chiave:
            df.loc[df['keywords'].str.contains(parola_chiave, case=False), 'category'] = categoria

    # Visualizza il DataFrame con le categorie assegnate
    print(df[['keywords', 'category']])

    keyword_column = df.pop('category')
    df.insert(df.columns.get_loc('keywords') + 1, 'category', keyword_column)

    return df

